[package]
name = "proofbound-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "proofbound"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
proofbound-core = { path = "../proofbound-core" }
proofbound-evidence = { path = "../proofbound-evidence" }
proofbound-manifest = { path = "../proofbound-manifest" }
serde.workspace = true
serde_json.workspace = true
semver.workspace = true
sha2.workspace = true
tempfile.workspace = true
toml.workspace = true
walkdir.workspace = true

[dev-dependencies]
proofbound-adapter-node = { path = "../proofbound-adapter-node" }
proofbound-adapter-test = { path = "../proofbound-adapter-test" }
